apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - env:
        - name: CATALINA_OPTS
          value: -Dconfig.apmServerDefault=Classic -Xmx525m
        - name: ET_BACKEND_URL
          value: http://backend:8080
        image: dynatrace/easytravel-frontend
        name: frontend
        ports:
        - containerPort: 8080
        resources: {}
      hostname: easytravel-frontend
      restartPolicy: Always
status: {}
