apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: loadgen
  name: loadgen
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: loadgen
    spec:
      containers:
      - env:
        - name: ET_APM_SERVER_DEFAULT
          value: Classic
        - name: ET_BACKEND_URL
          value: http://www:8080
        - name: ET_FRONTEND_URL
          value: http://www:80
        - name: ET_PROBLEMS
          value: BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox
        image: dynatrace/easytravel-loadgen
        name: loadgen
        resources: {}
      restartPolicy: Always
status: {}
